# Generated by Django 3.1.1 on 2020-09-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_auto_20200908_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rent_per_day',
        ),
    ]
