# Generated by Django 3.1.1 on 2020-09-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='regular', max_length=100)),
                ('type_price', models.DecimalField(decimal_places=2, default=1.5, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/book_store'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store.booktype'),
        ),
    ]
