# Generated by Django 3.1.1 on 2020-09-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0006_auto_20200910_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktype',
            name='promotional_period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booktype',
            name='promotional_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
