# Generated by Django 3.1.1 on 2020-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_auto_20200910_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='promotional_price',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
